let num = prompt("Digite um número: ");

if (num < 10)
{
     alert("O numero digitado é menor do que 10!");
}
    else
if (num > 10 && num < 100)
{
    alert("O numero digitado é maior do que 10!");
}
    else 
if (num < 100)
{
    alert("O numero digitado é menor do que 100!");
}
    else
if (num > 100)
{
    alert("O numero digitado é maior do que 100!");
}


/*
if (num > 1000) 
    alert("O numero digitado é maior do que mil!");    
} 
else 
{
    alert("O numero digitado é menor do que mil!");
}*/